package phonebook;

import Conn_db.Conexion;
import phonebook.EditSU;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
/**
 *
 * @author JEscalona
 */
public class Interface_III extends javax.swing.JFrame {

    //Instancia de Conexion
    Conexion cn =new Conexion();

    private int RowSelection;
    
    Connection Conn;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    
    public Interface_III() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/1-ISOTIPO XDV pequeño.png")).getImage());
        setLocationRelativeTo(null);
        query();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agg1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pantalla = new javax.swing.JPanel();
        jBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_log_out = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        btn_drop = new javax.swing.JButton();
        btn_agg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btn_edit = new javax.swing.JButton();

        btn_agg1.setBackground(new java.awt.Color(0, 0, 51));
        btn_agg1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_agg1.setForeground(new java.awt.Color(204, 204, 204));
        btn_agg1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEscalona\\Documents\\NetBeansProjects\\APK\\src\\main\\java\\images\\Agguser.png")); // NOI18N
        btn_agg1.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 610));

        Pantalla.setBackground(new java.awt.Color(252, 249, 249));

        jBuscar.setBackground(new java.awt.Color(250, 237, 237));
        jBuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBuscar.setForeground(new java.awt.Color(204, 204, 204));
        jBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });
        jBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jBuscarKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Setting SU");

        btn_log_out.setBackground(new java.awt.Color(255, 204, 204));
        btn_log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        btn_log_out.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_log_outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_log_outMouseExited(evt);
            }
        });
        btn_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_outActionPerformed(evt);
            }
        });

        btn_volver.setBackground(new java.awt.Color(255, 204, 204));
        btn_volver.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_volver.setForeground(new java.awt.Color(204, 204, 204));
        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volver.png"))); // NOI18N
        btn_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_volverMouseExited(evt);
            }
        });
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });

        btn_drop.setBackground(new java.awt.Color(255, 204, 204));
        btn_drop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash.png"))); // NOI18N
        btn_drop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_drop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dropMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dropMouseExited(evt);
            }
        });
        btn_drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dropActionPerformed(evt);
            }
        });

        btn_agg.setBackground(new java.awt.Color(255, 204, 204));
        btn_agg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Agguser.png"))); // NOI18N
        btn_agg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_agg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aggMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_aggMouseExited(evt);
            }
        });
        btn_agg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btn_edit.setBackground(new java.awt.Color(255, 204, 204));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btn_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editMouseExited(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaLayout = new javax.swing.GroupLayout(Pantalla);
        Pantalla.setLayout(PantallaLayout);
        PantallaLayout.setHorizontalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaLayout.createSequentialGroup()
                .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PantallaLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PantallaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PantallaLayout.createSequentialGroup()
                                .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(252, 252, 252)
                                .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_agg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PantallaLayout.createSequentialGroup()
                                    .addComponent(btn_volver)
                                    .addGap(91, 91, 91)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PantallaLayout.setVerticalGroup(
            PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_volver))
                .addGap(18, 18, 18)
                .addComponent(jBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PantallaLayout.createSequentialGroup()
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PantallaLayout.createSequentialGroup()
                        .addComponent(btn_agg, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_drop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 370, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_outActionPerformed
        // btn_volver
        Login Lg =new Login();
        Lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_log_outActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        // btn_vover
        Interface_II InterII =new Interface_II();
        InterII.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    private void btn_dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dropActionPerformed
        // btn_drop
        dropDt();
        
    }//GEN-LAST:event_btn_dropActionPerformed

    private void btn_aggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggActionPerformed
        // btn_agg
        Uloap Ul =new Uloap();
        Ul.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_aggActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // seatch

    }//GEN-LAST:event_jBuscarActionPerformed

    private void jBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode()== KeyEvent.VK_ENTER ){
            query();
        }

    }//GEN-LAST:event_jBuscarKeyPressed

    private void jBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyReleased
        // Busqueda en tiempo real
        if(jBuscar.getText().trim().equals("")); {
            query();
        }

    }//GEN-LAST:event_jBuscarKeyReleased

    private void jBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBuscarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jBuscarKeyTyped

    private void btn_log_outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_log_outMouseEntered
        // Efecto Hover
        btn_log_out.setBackground(new Color(210,127,127));
    }//GEN-LAST:event_btn_log_outMouseEntered

    private void btn_log_outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_log_outMouseExited
        // Salida de Hover
        btn_log_out.setBackground(new Color(255,204,204,204));
    }//GEN-LAST:event_btn_log_outMouseExited

    private void btn_volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseEntered
        // Efecto Hover
        btn_volver.setBackground(new Color(210,127,127));
    }//GEN-LAST:event_btn_volverMouseEntered

    private void btn_volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_volverMouseExited
        // Salida de Hover
        btn_volver.setBackground(new Color(255,204,204,204));
    }//GEN-LAST:event_btn_volverMouseExited

    private void btn_dropMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dropMouseEntered
        // Efecto Hover
        btn_drop.setBackground(new Color(210,127,127));
    }//GEN-LAST:event_btn_dropMouseEntered

    private void btn_dropMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dropMouseExited
        // Salida de Hover
        btn_drop.setBackground(new Color(255,204,204,204));
    }//GEN-LAST:event_btn_dropMouseExited

    private void btn_aggMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aggMouseEntered
        // Efecto Hover
        btn_agg.setBackground(new Color(210,127,127));
    }//GEN-LAST:event_btn_aggMouseEntered

    private void btn_aggMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aggMouseExited
        // Salida de Hover
        btn_agg.setBackground(new Color(255,204,204,204));
    }//GEN-LAST:event_btn_aggMouseExited

    private void btn_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseEntered
        // Efecto Hover
        btn_edit.setBackground(new Color(210,127,127));
    }//GEN-LAST:event_btn_editMouseEntered

    private void btn_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseExited
        // Salida de Hover
        btn_edit.setBackground(new Color(255,204,204,204));
    }//GEN-LAST:event_btn_editMouseExited

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // btn Edit
        modificar();
    }//GEN-LAST:event_btn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_III.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_III.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_III.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_III.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_III().setVisible(true);
            }
        });
    }
    
    //Metodo Vistas
    
    /*
    void query(){
        String sql = " SELECT *FROM p_list_phone_log";
        
        try{
            Conn = cn.conectar();
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            Object[] arreglo = new Object[5];
            modelo = (DefaultTableModel) Tabla.getModel();
            while (rs.next()) {
                arreglo [0] = rs.getInt("id");
                arreglo [1] = rs.getString("name");
                arreglo [2] = rs.getString("surname");
                arreglo [3] = rs.getString("password");
                arreglo [4] = rs.getString("roll");
                
                modelo.addRow(arreglo);
            }
            Tabla.setModel(modelo);
            
        } catch (Exception e){
            
        }
    }
    */
    
    //Metodo query
    private void query(){
        String busqueda = jBuscar.getText();
        
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
           public boolean isCellEditable(int row, int column) {
               if (column==0) {
                   return true;
               } else {
                    return false;
               }    
           }
        };
        
        
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Pass");
        modelo.addColumn("Roll");
        
        Tabla.setModel(modelo);
        Tabla.getColumnModel().getColumn(0).setPreferredWidth(20);
        Tabla.getColumnModel().getColumn(1);
        Tabla.getColumnModel().getColumn(2);
        Tabla.getColumnModel().getColumn(3);
        Tabla.getColumnModel().getColumn(4);
            
       String sql = "SELECT *FROM log_phone WHERE NAME LIKE '%"+busqueda+"%' OR SURNAME LIKE '%"+busqueda+"%' OR ROLL LIKE '%"+busqueda+"%' ";
        
        String datos [] = new String [5];
        
        try {
            Conn =  cn.conectar();
            st = Conn.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                datos [0] = rs.getString("id");
                datos [1] = rs.getString("name");
                datos [2] = rs.getString("surname");
                datos [3] = rs.getString("password");
                datos [4] = rs.getString("roll");
                
                modelo.addRow(datos);
            }
            
            Tabla.setModel(modelo);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    //Edit
    public void modificar(){
        int rowE =Tabla.getSelectedRow();
            if(rowE>=0){
                EditSU ESU=new EditSU();
                ESU.setVisible(true);
                this.setVisible(false);
                
               //Import datos EditSU 
               ESU.SetModificationid(Tabla.getValueAt(rowE,0).toString());
               ESU.setModification1(Tabla.getValueAt(rowE,1).toString());
               ESU.setModification2(Tabla.getValueAt(rowE,2).toString());
               ESU.setModification3((Tabla.getValueAt(rowE,3).toString()));
               ESU.setModification4((Tabla.getValueAt(rowE,4).toString()));

            } else{
                JOptionPane.showMessageDialog(null, "Seleccione almenos un Registro");
            }
    }
    
    
    //Drop
    public void dropDt(){
        try {
        
            int fila = Tabla.getSelectedRow();
            
            String sql = " DELETE FROM log_phone WHERE id=" +Tabla.getValueAt(fila, 0);
            
            Statement st = Conn.createStatement();
            
            int n=st.executeUpdate(sql);
            
            if (n>=0) {
                JOptionPane.showMessageDialog(null, "Este usario ha sido Eliminado!");
                Interface_III InterIII =new Interface_III();
                InterIII.setVisible(true);
                this.setVisible(false);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha Ocurrido un Error, debe selecionar almenos un registro!" +e.getMessage());
        }

    }
    
    //Metodo Edit 
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pantalla;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btn_agg;
    private javax.swing.JButton btn_agg1;
    private javax.swing.JButton btn_drop;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_log_out;
    private javax.swing.JButton btn_volver;
    private javax.swing.JTextField jBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
